# Use the official Python image with Ubuntu base
FROM python:3.12-alpine

# Set the working directory
WORKDIR /app

# Update packages and install necessary dependencies
# RUN apt-get update && \
#     apt-get clean && rm -rf /var/lib/apt/lists/*

# Install additional Python dependencies from requirements file
COPY requirements.txt /app/requirements.txt
RUN python3 -m ensurepip --upgrade && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY app /app

# Expose the port the app runs on
EXPOSE 8080

# Set the entrypoint
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]